package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendao.Shopping;

import greendao.ShoppingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingDaoConfig;

    private final ShoppingDao shoppingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingDaoConfig = daoConfigMap.get(ShoppingDao.class).clone();
        shoppingDaoConfig.initIdentityScope(type);

        shoppingDao = new ShoppingDao(shoppingDaoConfig, this);

        registerDao(Shopping.class, shoppingDao);
    }
    
    public void clear() {
        shoppingDaoConfig.clearIdentityScope();
    }

    public ShoppingDao getShoppingDao() {
        return shoppingDao;
    }

}
